### ISSUE TITLE
Can I ask where is the entry on Gradescope for homework submission?

### ISSUE THREAD

**Issue by sheyehs** [pliugithub/MachineLearning#10]
It is my first time to use Gradescope, and I notice that the homework for course 02 is due on Sep 20th. But in my web page, I cannot find any entry to submit the homework. Thanks for help me!
![image](https://github.com/pliugithub/MachineLearning/assets/111511543/2cea3a89-884c-40f3-b682-088a47c69dd8)

**Comment by pliugithub** [comment]
It will be created this weekend.

Thanks.
