### ISSUE TITLE
Corrections Needed of Due Dates in Syllabus

### ISSUE THREAD

**Issue by Herts** [pliugithub/MachineLearning#6]
Hi Prof. Pei,
Could you update the due dates in the [syllabus](https://github.com/pliugithub/MachineLearning/blob/master/sequence.md) as in 2022 Fall?

**Comment by popkarthb** [comment]
> 

Usually Due date will be release by TA in Grade scope.

**Comment by Herts** [comment]
> 

Thanks for the clarification
